### PR TITLE
truncate crash log string to 60000 characters

### LINKED ISSUE #82: Notice not posted successfully because "Request body too large"
I'm using RubyMotion and while `writeTestNotice` works, a real crash generates a crash log size of the order of 82k. Looking at https://airbrake.io/docs/api/#create-notice-v3, it appears that the limit is 64kb. Is there a way around this?

### PR DESCRIPTION
**Pull request by juergenm**
to fix "Request body to large" error. fixes #82

### CODE REVIEW

File: Airbrake/notifier/ABNotifier.m [hunk 1]
```diff
@@ -527,6 +527,14 @@ + (NSData *)JSONString:(NSString *)filePath {
     NSError *error = NULL;
     NSError *jsonSerializationError = nil;
     NSString *dataStr = [[NSString alloc] initWithContentsOfFile:filePath encoding:NSUTF8StringEncoding error:&error];
+    
+    // chrash reports seems to be limited to 64kb, otherwise they are ignored by the API with the following error
+    // [Airbrake] {"code":400,"type":"Bad Request","message":"http: request body too large"}
+    // so we truncate the string to 60000 characters
+    if(dataStr.length > 60000) {
```
Comment (kyrylo) [inline Airbrake/notifier/ABNotifier.m]: 1. Our API limit is 64KB, not 60000 characters, hence this is not the most precise check
2. Looks like you truncate a string. We need to check dumped JSON if it's bigger than 64KB and then truncate payload in the notice object

**Comment by juergenm** [comment]
@kyrylo Thats true this check was not very precise. I now first create the JSON, check the size and if it is too large i truncate the payload string

**Comment by jocelynlih** [comment]
This looks good to me. My only concern is that the size limit is hardcoded in the API. 
But I suppose it won't get updated/changed unless a new API version is used? @kyrylo

**Comment by kyrylo** [comment]
@jocelynlih that's a correct assumption. We hardcode this in every notifier that supports this feature.

**Comment by kyrylo** [comment]
Thanks, @juergenm!

**Comment by juergenm** [comment]
@kyrylo thanks for merging, could you please release a new version so that I can use it with CocoaPods.
